repos:
  - repo: local
    hooks:
      - id: lint-frontmatter
        name: Lint Markdown Frontmatter
        entry: scripts/lint-frontmatter.rb
        language: script
        files: '\.(md|markdown)$'
