# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Donkey Does Write v2
email:
description: >- # this means to ignore newlines until "baseurl:"
  A blog of Vitor Zhou
twitter_username: ZainanZhou
github_username: xinbenlv
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Victor Zhou"
  avatar : "/assets/images/zzn-pic.jpeg"
  bio    : "Founder & CEO at D3Serve Labs, Ethereum EIP Editor, Open standard advocate, smart contract architect, ex-Googler, Alumni of Tsinghua U, Johns Hopkins U, Microsoft Research, Investor w/ AlephCrypto.xyz"
  links:
    - label: "D3Cards"
      icon: "fas fa-fw fa-link"
      url: "https://d3.cards/@ZainanZhou"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/ZainanZhou"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/xinbenlv"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/ZainanZhou"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/xinbenlv"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-GJB6TXQ81S"
    anonymize_ip: false # default